services:
  web:
    build: .
    command: sh -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./:/app
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_HOST=typesense
      - TYPESENSE_PORT=8108
      - TYPESENSE_PROTOCOL=http
    ports:
      - "8002:8000"
    depends_on:
      - typesense

  typesense:
    image: typesense/typesense:0.25.1
    environment:
      - TYPESENSE_API_KEY=xyz
      - TYPESENSE_DATA_DIR=/data
      - TYPESENSE_ENABLE_CORS=true
    volumes:
      - ./typesense-data:/data
    ports:
      - "8108:8108"
